### ISSUE TITLE
运行环境配置问题 TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by xiangtianshi** [huyinghuan/lottery-2016#2]
尝试按照Readme中的指导说明在一台全新的 ubuntu 16.04.1-desktop-amd64 中操作。 
并按照提示安装了
sudo apt-get install npm
sudo npm install node-dev -g
sudo npm install coffee-script -g
vi config.coffee
vi init-data.coffee
sudo ln /usr/bin/nodejs  /usr/bin/node
npm install fs-extra
npm install lodash
npm install coal
npm install sqlite3

初始化的时候提示错误
xiang@xiang:~/lottery-2016-master$ coffee init-data.coffee 
Create award begin !
Create employee begin !
Create award success !
Create lottery begin !
Create employee success !
Create lottery success !
/home/xiang/lottery-2016-master/init-data.coffee:29
        num = num.replace(/\s/g, "");
                 ^
TypeError: Cannot read property 'replace' of undefined
    at /home/xiang/lottery-2016-master/init-data.coffee:29:18
    at FSReqWrap.oncomplete (fs.js:82:15)

当我尝试注释掉 # num = num.replace(/\s/g, "") 继续初始化，提示照片插入失败
xiang@xiang:~/lottery-2016-master$ coffee init-data.coffee
--- Update table award begin...
--- Update table employee begin...
--- Update table lottery begin...
--- Update table award finish.
--- Update table lottery finish.
--- Update table employee finish.
error! zhang3.jpg
本次插入0
所有数据插入成功！
[ { 'count(*)': 1 } ]

然后通过网页开始抽奖的时候自然不显示头像，也没有气球， 按回车也没有停止的反应。
不知道如何能够解决以上问题。

**Comment by huyinghuan** [comment]
![image](https://cloud.githubusercontent.com/assets/3005433/22089929/6e2fab1c-de29-11e6-886b-d5d12e978341.png)
这个错误表明你的员工照片没有按要求  `姓名_工号.png`  格式进行命名

**Comment by huyinghuan** [comment]
运行下git pull 更新下代码，我修复了这个问题
